### ISSUE TITLE
Training and Inference on different Problem Types

### ISSUE THREAD

**Issue by EtashGuha** [zzhang1987/Factor-Graph-Neural-Network#2]
Is there a way to train and test on different problem types such as Vertex Cover?

**Comment by zzhang1987** [comment]
Particularly for Vertex Cover problem, the answer is yes. However, it may not be a good idea to use it for supervised learning to solve the Vertex Cover problem. It might be better to use FGNN along with RL algorithms such as Q-learning or A3C, otherwise it would be not easy to enforce the prediction to be feasible.

**Comment by EtashGuha** [comment]
How would I perform inferrence using fgnn on different problems? I see within the code you break the parts of the dataset into nodefeatures and edgefeatures, but I do not see where the structure of the graph would embedded within the training. Is that the KNN Table?

**Comment by EtashGuha** [comment]
I also get this error when I run any of the files:
```
/Users/etashguha/anaconda3/envs/Research/bin/python /Users/etashguha/Documents/Factor-Graph-Neural-Network/train_syn_hop_factor.py
Traceback (most recent call last):
  File "/Users/etashguha/Documents/Factor-Graph-Neural-Network/train_syn_hop_factor.py", line 1, in <module>
    import lib
  File "/Users/etashguha/Documents/Factor-Graph-Neural-Network/lib/__init__.py", line 1, in <module>
    import lib.data
  File "/Users/etashguha/Documents/Factor-Graph-Neural-Network/lib/data/__init__.py", line 1, in <module>
    import lib.data.ldpc
  File "/Users/etashguha/Documents/Factor-Graph-Neural-Network/lib/data/ldpc.py", line 2, in <module>
    from .MNC import s2t, t2y, y2b, zb2x, init_seed
  File "/Users/etashguha/Documents/Factor-Graph-Neural-Network/lib/data/MNC/__init__.py", line 1, in <module>
    from .MNC import init_seed, s2t, t2y, y2b, zb2x
ModuleNotFoundError: No module named 'lib.data.MNC.MNC'
```

**Comment by zzhang1987** [comment]
This is because the MNC module (which is a submodule) is not compiled. I will update the readme about this part as soon as possible.

**Comment by zzhang1987** [comment]
> I also get this error when I run any of the files:
> 
> ```
> /Users/etashguha/anaconda3/envs/Research/bin/python /Users/etashguha/Documents/Factor-Graph-Neural-Network/train_syn_hop_factor.py
> Traceback (most recent call last):
>   File "/Users/etashguha/Documents/Factor-Graph-Neural-Network/train_syn_hop_factor.py", line 1, in <module>
>     import lib
>   File "/Users/etashguha/Documents/Factor-Graph-Neural-Network/lib/__init__.py", line 1, in <module>
>     import lib.data
>   File "/Users/etashguha/Documents/Factor-Graph-Neural-Network/lib/data/__init__.py", line 1, in <module>
>     import lib.data.ldpc
>   File "/Users/etashguha/Documents/Factor-Graph-Neural-Network/lib/data/ldpc.py", line 2, in <module>
>     from .MNC import s2t, t2y, y2b, zb2x, init_seed
>   File "/Users/etashguha/Documents/Factor-Graph-Neural-Network/lib/data/MNC/__init__.py", line 1, in <module>
>     from .MNC import init_seed, s2t, t2y, y2b, zb2x
> ModuleNotFoundError: No module named 'lib.data.MNC.MNC'
> ```

I have updated the readme. After compiling the MNC module it should be ok to run the program in MacOS. However, for best practice I recommend you to build and run the program in Linux.
