### ISSUE TITLE
pytorch version 

### ISSUE THREAD

**Issue by kangyang73** [zzhang1987/Factor-Graph-Neural-Network#4]
If the model is trained by CPU,  there is no Exception error. But if I enable CUDA, there is always an error, RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED. 

my environment: pytorch: 1.5.1+cu101
                                           CUDA 10.1

**Comment by zzhang1987** [comment]
May I know you hardware environment? It is very likely that you are using cuda10 on unsupported environments such as RTX 3090.

**Comment by kangyang73** [comment]
it is GeForce RTX 3080 Ti.

**Comment by zzhang1987** [comment]
Then it would not be possible to use CUDA10, you will have to use CUDA11.

**Comment by kangyang73** [comment]
Thanks for your answer.
